version: '3.6'

services:

  # Front End
  smart-brain-front-end:
    container_name: smartbrain-front_end
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    command: npm start
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - 3001:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - smartbrain-net

networks:
  smartbrain-net:
    external:
      name: backend_network
